//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFTestingTool {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Windows\\Temp\\TempProxy.dll")]
        public string ProxyAssemblyPath {
            get {
                return ((string)(this["ProxyAssemblyPath"]));
            }
            set {
                this["ProxyAssemblyPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/directory:C:\\Windows\\Temp /out:TempProxy.cs /config:app.config")]
        public string SvcCmdParameter {
            get {
                return ((string)(this["SvcCmdParameter"]));
            }
            set {
                this["SvcCmdParameter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Microsoft SDKs\\Windows\\v7.0A\\bin\\SvcUtil.exe")]
        public string SvcUtilFilePath {
            get {
                return ((string)(this["SvcUtilFilePath"]));
            }
            set {
                this["SvcUtilFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" /t:library /out:C:\\Windows\\Temp\\TempProxy.dll  C:\\Windows\\Temp\\TempProxy.cs")]
        public string CscCmdParameter {
            get {
                return ((string)(this["CscCmdParameter"]));
            }
            set {
                this["CscCmdParameter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\WINDOWS\\Microsoft.NET\\Framework\\v3.5\\csc.exe")]
        public string CscFilePath {
            get {
                return ((string)(this["CscFilePath"]));
            }
            set {
                this["CscFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("System.ServiceModel.ClientBase`1")]
        public string BaseServiceClassName {
            get {
                return ((string)(this["BaseServiceClassName"]));
            }
            set {
                this["BaseServiceClassName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CreateChannel")]
        public string CreateChannel {
            get {
                return ((string)(this["CreateChannel"]));
            }
            set {
                this["CreateChannel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Client")]
        public string Client {
            get {
                return ((string)(this["Client"]));
            }
            set {
                this["Client"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Windows\\Temp\\TempProxy.cs")]
        public string ProxyClassPath {
            get {
                return ((string)(this["ProxyClassPath"]));
            }
            set {
                this["ProxyClassPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Sources (*.config, *.xml)|*.config*;*.xml|All Files|*.*")]
        public string ConfigFileFilter {
            get {
                return ((string)(this["ConfigFileFilter"]));
            }
            set {
                this["ConfigFileFilter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".config")]
        public string ConfigFileExt {
            get {
                return ((string)(this["ConfigFileExt"]));
            }
            set {
                this["ConfigFileExt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Windows\\Temp\\app.config")]
        public string ConfigFilePath {
            get {
                return ((string)(this["ConfigFilePath"]));
            }
            set {
                this["ConfigFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Methods have been loaded successfully. Please select any method to run.")]
        public string MethodLoadedSuccess {
            get {
                return ((string)(this["MethodLoadedSuccess"]));
            }
            set {
                this["MethodLoadedSuccess"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Error while generating proxy or loading methods. May be the service is not runing" +
            " at the given end point address.")]
        public string GeneratingProxyFail {
            get {
                return ((string)(this["GeneratingProxyFail"]));
            }
            set {
                this["GeneratingProxyFail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Finding the service please wait...")]
        public string FindingService {
            get {
                return ((string)(this["FindingService"]));
            }
            set {
                this["FindingService"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EmptyString {
            get {
                return ((string)(this["EmptyString"]));
            }
            set {
                this["EmptyString"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Service found.")]
        public string ServiceFound {
            get {
                return ((string)(this["ServiceFound"]));
            }
            set {
                this["ServiceFound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Type")]
        public string Type {
            get {
                return ((string)(this["Type"]));
            }
            set {
                this["Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Name")]
        public string Name {
            get {
                return ((string)(this["Name"]));
            }
            set {
                this["Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Value")]
        public string Value {
            get {
                return ((string)(this["Value"]));
            }
            set {
                this["Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("System.Runtime.Serialization.ExtensionDataObject")]
        public string ExtensionDataObject {
            get {
                return ((string)(this["ExtensionDataObject"]));
            }
            set {
                this["ExtensionDataObject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("extensionDataField")]
        public string ExtensionDataField {
            get {
                return ((string)(this["ExtensionDataField"]));
            }
            set {
                this["ExtensionDataField"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Loading the methods please wait...")]
        public string LoadingMethodWait {
            get {
                return ((string)(this["LoadingMethodWait"]));
            }
            set {
                this["LoadingMethodWait"] = value;
            }
        }
    }
}
